export const menuItems = [
  {
    id: 1,
    label: "documentation.leftContainer.Introduction",
    hasIcon: false,
  },
  {
    id: 2,
    label: "documentation.leftContainer.overview",
    hasIcon: true,
    subItems: [
      "First Steps",
      "Controllers",
      "Providers",
      "Modules",
      "Middleware",
      "Exception filters",
      "Pipes",
      "Guards",
      "Interceptors",
      "Custom Decorators",
    ],
  },
  {
    id: 3,
    label: "documentation.leftContainer.fundamentals",
    hasIcon: true,
    subItems: ["Custom providers", "Asynchronous providers"],
  },
  {
    id: 4,
    label: "Techniques",
    hasIcon: true,
    subItems: ["Custom providers", "Asynchronous providers"],
  },
  {
    id: 5,
    label: "Security",
    hasIcon: true,
    subItems: ["Custom providers", "Asynchronous providers"],
  },
  {
    id: 6,
    label: "GraphQL",
    hasIcon: true,
    subItems: ["Custom providers", "Asynchronous providers"],
  },
  {
    id: 7,
    label: "WebSockets",
    hasIcon: true,
    subItems: ["Custom providers", "Asynchronous providers"],
  },
  {
    id: 8,
    label: "Microservices",
    hasIcon: true,
    subItems: ["Custom providers", "Asynchronous providers"],
  },
  {
    id: 9,
    label: "Standalone Apps",
    hasIcon: true,
    subItems: ["Custom providers", "Asynchronous providers"],
  },
  {
    id: 10,
    label: "CLI",
    hasIcon: true,
    subItems: ["Custom providers", "Asynchronous providers"],
  },
  {
    id: 11,
    label: "OpenAPI",
    hasIcon: true,
    subItems: ["Custom providers", "Asynchronous providers"],
  },
  {
    id: 12,
    label: "Recipes",
    hasIcon: true,
    subItems: ["Custom providers", "Asynchronous providers"],
  },
];
